#!/usr/bin/env bash

# main
alias g='git'; source /usr/share/bash-completion/completions/git; __git_complete g __git_main;

# Git Related
alias gst="git status"
alias gc="git commit"
alias gcm="git commit -m"
alias gpl="git pull"
alias gp="git push"
alias gf="git fetch"
alias gfp="git fetch -p"
alias glsb="git branch -la"
alias gbd="git branch -d"
alias gshls="git stash list"
alias gshp="git stash pop"
alias gstat="git status"
alias gcb="git checkout -b"
alias ga="git add"

# worktrees
alias wtl="wt-list"

untouchableBranches="main|master|devel|staging"
alias gvmb="gfp && git branch --merged | grep -Ev '$untouchableBranches' >/tmp/merged-branches-$(basename $PWD) && nano /tmp/merged-branches-$(basename $PWD)"
alias gdelmb="echo '=> This command will show a list of branches and remove them from local remote...' && read -p '=> Press enter to continue...' && nano /tmp/merged-branches-$(basename $PWD) && xargs git branch -d </tmp/merged-branches-$(basename $PWD) && rm /tmp/merged-branches-$(basename $PWD)"

# Get default Github .gitignore
get-ignore() {
    if [ -z $1 ]; then
        # echo -e "get-ignore: Retrieve official Github .gitignore for a Lang\n"
        # echo -e "ERROR: Missing parameter <lang>\n"
        # echo "Usage:"
        # echo "      get-ignore <Lang>     | Pass the Lang variable as first parameter. (Capital Case)"
        # return
        local selected=$(echo "Perl Python Node" | tr ' ' '\n' | fzf)
        local variable="$(curl -s "https://www.toptal.com/developers/gitignore/api/$selected")"
        echo "$variable" | tail -n +4 | head -n -1 > .gitignore
    else
        local variable="$(curl -s "https://www.toptal.com/developers/gitignore/api/$1")"
    fi

    echo -e '\n'
}