#!/usr/bin/env bash

# Windows related
alias windoc="cd /mnt/c/Users/gabri/Documents"

# Alias Management related
alias resrc="source ~/.bashrc"
alias edalias="vim ~/.bash_aliases"
alias lsalias="cat ~/.bash_aliases"

# Terminal related
alias clc="clear"
alias clr="clear"
alias cls="clear"
alias ..="cd .."
alias ...="cd ../.."

# overriwite cd with z
alias cd="z"

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lx='ls -l'

alias upup="sudo apt update && sudo apt upgrade"

alias python="python3"

sweb() {
    open "https://www.bing.com/search?q=$@"
}

# short hand for history
alias h='history'
alias hl='history | less'
alias hs='history | rg'
alias hsi='history | rg -i'
