#!/usr/bin/env bash

# Windows related
alias windoc="cd /mnt/c/Users/gabri/Documents"

# Alias Management related
alias resrc="source ~/.bashrc"
alias edalias="nano ~/.bash_aliases"
alias lsalias="cat ~/.bash_aliases"

# Terminal related
alias clc="clear"
alias clr="clear"
alias cls="clear"
alias ..="cd .."
alias ...="cd ../.."

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lx='ls -l'

alias upup="sudo apt update && sudo apt upgrade"


alias python="python3"
